# Generated by Django 3.0.7 on 2020-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('large', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='big',
            new_name='large',
        ),
        migrations.CreateModel(
            name='AdditionalSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subs', models.ManyToManyField(blank=True, related_name='additional', to='orders.Subs')),
            ],
        ),
    ]
